maxPlayersInClan: 3 # from 2 to 28
messages:
  notPlayer: "§cYou are not a player!"
  alreadyInClan: "§cYou are already a part of a clan!"
  notInClan: "§cYou aren't in a clan!"
  noArgs: "§cNot enough args!"
  noPerm: "§cYou don't have permission to run this command!"
  scNotFound: "§cSubcommand not found!"
  clanCreated: "§aClan created!"
  clanMembers: "§7%value% members" # value = member count
  clanName: "§f%value%"
  disbanded: "§eClan disbanded!"
  noPlayer: "§c%value% not found!" # value = player's name
  inviteSent: "§aInvite sent successfully!"
  gotInvite: "<gold>You got an invite to the %value% clan!\nClick here to accept: <accept>" # value = clan name <accept> = button
  acceptInviteButton: "[Accept]"
  joined: "§a%value% has joined this clan!" # value = joined player's name
  promoted: "§a%value% got promoted!" # value = the player's name who got promoted
  demoted: "§c%value% got demoted!" # value = the player's name who got demoted
  transferred: "§e%value% became the new owner of the clan!" # value = the player's name who became owner
  clanFull: "§cThe clan is full! You can't invite anymore members."
  clanBecameFull: "§cThe clan you are trying to join became full. (Probably two invites were sent with one place left and the other player joined sooner.)"
  kicked: "§c%value% got kicked out of the clan." # value = kicked player's name
  left: "§e%value% left the clan" # value = value = left player's name
  cantLeaveOwn: "§cYou can't leave your own clan! If you really want to leave tho, use /clan disband or /clan transfer <player>"
guis:
  MyClanGUI:
    title: "My clan"
roles:
  OWNER: "§4Owner"
  ADMIN: "§cAdmin"
  MEMBER: "§7Member"
data:
  clans: {}